### ISSUE TITLE
Text Widget not able to display field of string.

### ISSUE THREAD

**Issue by IanTsuki** [Mehradzie/mdot_lora_arduino#28]
Data Sent:
```"{""L"":0}"```
<img width="393" alt="workingwidget" src="https://cloud.githubusercontent.com/assets/14935253/25464922/7e815d42-2b42-11e7-97fc-fad28ae9c6a6.png">

Data Sent:
```"{""L"":Movement Not Present}"```

Widget remains the same and does not update to display the string.

**Comment by lennon101** [comment]
Only after clicking “configure” does Altoview register the new field. You then need to hit “save” to save the new field to Altoview. 

![capture1](https://cloud.githubusercontent.com/assets/1709944/25511678/9427bbc2-2c0b-11e7-8c08-d271bc5b1e1a.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1709944/25511686/abf3f126-2c0b-11e7-863f-e1b87522bfab.PNG)

Editing the widget now shows the new field.

![capture3](https://cloud.githubusercontent.com/assets/1709944/25511700/c3e1428e-2c0b-11e7-9a33-bfb4e0663156.PNG)

**Comment by lennon101** [comment]
Thanks for the post! I noticed that the data you were sending was not quoted. Please ensure you quote the text that is to be sent as a field. Also please ensure you escape the quotes like this: 

`mdot.sendPairs("test:\"hey\"");`

Note the use of `\"` before the word `hey` and after. This will resolve your problem. 

![capture4](https://cloud.githubusercontent.com/assets/1709944/25512107/b2c1101c-2c0e-11e7-999f-10e3f83a56a2.PNG)


To be clear, your CSV file must look like this: 
![image](https://cloud.githubusercontent.com/assets/1709944/25512151/f4f8029c-2c0e-11e7-8063-7262cac70286.png)


**NOT THIS**
![image](https://cloud.githubusercontent.com/assets/1709944/25512159/066167d0-2c0f-11e7-9f8a-f2e8c0027b93.png)

In your case: 
Data Sent:
`"{""L"":0}"` --> worked because `0` is an integer and can be properly cast to a string

Data Sent:
`"{""L"":Movement Not Present}"` --> not an Integer nor is it a String because the `Movement Not Present` is not quoted like this: `"Movement Not Present"`
